name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run .NET tests
        working-directory: MeiliNameSearch
        run: |
          dotnet test tests/NameSearch.Tests/NameSearch.Tests.csproj --no-build --verbosity normal || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run frontend tests (if present)
        working-directory: MeiliNameSearch/MeiliNameSearchReact
        run: |
          if [ -f package.json ]; then
            if grep -q "\"test\"" package.json; then
              npm ci
              npm test
            else
              echo "No frontend tests defined, skipping"
            fi
          fi

  build-and-deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: MeiliNameSearch/MeiliNameSearchReact
        run: npm ci

      - name: Build Main App
        working-directory: MeiliNameSearch/MeiliNameSearchReact
        run: npm run build

      - name: Install Dashboard Dependencies
        working-directory: meili-mini-dashboard
        run: npm ci

      - name: Build Dashboard
        working-directory: meili-mini-dashboard
        env:
          VITE_MEILI_HOST: https://meilisearch-latest-mhph.onrender.com
          VITE_MEILI_API_KEY: demo-key-please-configure-in-repository-secrets
        run: npm run build

      - name: Prepare Combined Deployment
        run: |
          mkdir -p combined-dist
          # Copy main app to root (keep existing URL working)
          cp -r MeiliNameSearch/MeiliNameSearchReact/dist/* combined-dist/
          # Copy dashboard to /dashboard subdirectory
          mkdir -p combined-dist/dashboard
          cp -r meili-mini-dashboard/dist/* combined-dist/dashboard/
          # Add dashboard link to main app (optional)
          echo "Dashboard available at: $(pwd)/combined-dist/dashboard/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: combined-dist
          clean: true
