name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run .NET tests
        working-directory: MeiliNameSearch
        run: |
          dotnet test tests/NameSearch.Tests/NameSearch.Tests.csproj --no-build --verbosity normal || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run frontend tests (if present)
        working-directory: MeiliNameSearch/MeiliNameSearchReact
        run: |
          if [ -f package.json ]; then
            if grep -q "\"test\"" package.json; then
              npm ci
              npm test
            else
              echo "No frontend tests defined, skipping"
            fi
          fi

  build-and-deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: MeiliNameSearch/MeiliNameSearchReact
        run: npm ci

      - name: Build Main App
        working-directory: MeiliNameSearch/MeiliNameSearchReact
        run: npm run build

      - name: Install Dashboard Dependencies
        working-directory: meili-mini-dashboard
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Using npm ci with existing package-lock.json"
            npm ci
          else
            echo "No package-lock.json found, using npm install"
            npm install
          fi

      - name: Build Dashboard
        working-directory: meili-mini-dashboard
        env:
          VITE_MEILI_HOST: https://meilisearch-latest-mhph.onrender.com
          VITE_MEILI_API_KEY: demo-key-please-configure-in-repository-secrets
        run: |
          # Build dashboard with correct base path for /dashboard/ subdirectory
          npm run build -- --base=/SmartNameSearch/dashboard/

      - name: Prepare Combined Deployment
        run: |
          echo "=== Preparing combined deployment ==="
          mkdir -p combined-dist
          
          # Copy main app to root (keep existing URL working)
          echo "Copying main app..."
          cp -r MeiliNameSearch/MeiliNameSearchReact/dist/* combined-dist/
          
          # Copy dashboard to /dashboard subdirectory
          echo "Copying dashboard..."
          mkdir -p combined-dist/dashboard
          cp -r meili-mini-dashboard/dist/* combined-dist/dashboard/
          
          # Debug: Show what was copied
          echo "=== Main app files ==="
          ls -la combined-dist/ | head -10
          echo "=== Dashboard files ==="
          ls -la combined-dist/dashboard/ | head -10
          
          # Verify dashboard index.html exists
          if [ -f "combined-dist/dashboard/index.html" ]; then
            echo "✅ Dashboard index.html found"
          else
            echo "❌ Dashboard index.html NOT found"
            echo "Contents of dashboard dist:"
            ls -la meili-mini-dashboard/dist/
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: combined-dist
          clean: true
